### ISSUE TITLE
ReferenceError: L is not defined

### ISSUE THREAD

**Issue by JeetuChoudhary** [BETOXL/ngx.leaflet.offline#1]
Hey, I am trying to use this plugin in my Ionic-angular Application and I am doing all the things mentioned in the doc and example. But, I am getting the following error and the map is not showing. 

> ERROR Error: Uncaught (in promise): ReferenceError: L is not defined
ReferenceError: L is not defined
    at MapDownloadComponent.createMap (map-download.component.ts:54:17)
    at MapDownloadComponent.<anonymous> (map-download.component.ts:25:10)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76:1
    at new ZoneAwarePromise (zone.js:1340:1)
    at __awaiter (tslib.es6.js:72:1)
    at MapDownloadComponent.initMap (map-download.component.ts:23:16)
    at MapDownloadComponent.ngOnInit (map-download.component.ts:20:10)
    at callHook (core.mjs:2526:1)
    at callHooks (core.mjs:2495:1)
    at resolvePromise (zone.js:1255:1)
    at new ZoneAwarePromise (zone.js:1343:1)
    at __awaiter (tslib.es6.js:72:1)
    at MapDownloadComponent.initMap (map-download.component.ts:23:16)
    at MapDownloadComponent.ngOnInit (map-download.component.ts:20:10)
    at callHook (core.mjs:2526:1)
    at callHooks (core.mjs:2495:1)
    at executeInitAndCheckHooks (core.mjs:2446:1)
    at refreshView (core.mjs:9484:1)
    at refreshEmbeddedViews (core.mjs:10594:1)

Any idea about what am I doing wrong?

**Comment by JeetuChoudhary** [comment]
resolved it
